LOAD DATA LOCAL INFILE '~/shared/project2/CS144-Part2/items-uniq.csv' 
INTO TABLE Items FIELDS TERMINATED BY '\t' OPTIONALLY ENCLOSED BY '"';

LOAD DATA LOCAL INFILE '~/shared/project2/CS144-Part2/location-info-uniq.csv' 
INTO TABLE LocationInfo FIELDS TERMINATED BY '\t' OPTIONALLY ENCLOSED BY '"';

LOAD DATA LOCAL INFILE '~/shared/project2/CS144-Part2/item-category-uniq.csv' 
INTO TABLE ItemCategory FIELDS TERMINATED BY '\t' OPTIONALLY ENCLOSED BY '"';

LOAD DATA LOCAL INFILE '~/shared/project2/CS144-Part2/sellers-uniq.csv' 
INTO TABLE Sellers FIELDS TERMINATED BY '\t' OPTIONALLY ENCLOSED BY '"';

LOAD DATA LOCAL INFILE '~/shared/project2/CS144-Part2/bidders-uniq.csv' 
INTO TABLE Bidders FIELDS TERMINATED BY '\t' OPTIONALLY ENCLOSED BY '"';

LOAD DATA LOCAL INFILE '~/shared/project2/CS144-Part2/bids-uniq.csv' 
INTO TABLE Bids FIELDS TERMINATED BY '\t' OPTIONALLY ENCLOSED BY '"';
